
import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import * as Auth from '@app/components/layouts/AuthLayout/AuthLayout.styles';
import { BaseForm } from '@app/components/common/forms/BaseForm/BaseForm';
import './PrivacyPolicyPage.css'; 

const PrivacyPolicyPage: React.FC = () => {
	const { t } = useTranslation();
	const navigate = useNavigate();
	return (
		<Auth.FormWrapper className="pp-container">
			<BaseForm>
				<BaseForm.Item noStyle>
					<Auth.BackWrapper onClick={() => navigate(-1)}>
						<Auth.BackIcon />
						{t('common.back')}
					</Auth.BackWrapper>
					<div className="pp-title">Privacy Policy</div>
					<div className="pp-sub-title">
						This is a statement that declares a firm's or website's policy on collecting and releasing information about a visitor. It usually declares what specific information is collected and whether it is kept confidential or shared with or sold to other firms, researchers or sellers.
					</div>
					<div className="pp-box">
						<div className="clear"></div>
						<h3>What information do we collect?</h3>
						<p>We collect information from you when you subscribe to our newsletter, respond to a survey, or fill out a form.</p>
						<p>When registering on our site, as appropriate, you may be asked to enter your: name, email address, phone number, country, company name, etc. You may, however, visit our site anonymously.</p>
						<h3>What do we use your information for?</h3>
						<p>Any of the information we collect from you may be used in one of the following ways:</p>
						<ul>
							<li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs).</li>
							<li>To send periodic emails.</li>
						</ul>
						<p>Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</p>
						<h3>Do we use cookies?</h3>
						<p>A cookie is a small piece of information that is placed on a user’s computer. A cookie will usually contain the name of the domain from which the cookie has come, the lifetime of the cookie, and a value, usually a randomly generated unique number. Cookies cannot be used to identify the user. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website.</p>
						<p>This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses cookies to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google will not associate your IP address with any other data held by Google. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
						<p>This website uses HubSpot, marketing automation software provide by HubSpot, Inc. (“HubSpot”). HubSpot uses cookies to collect information about how visitors use our site. We use the information gathered by these cookies to compile reports and to help us improve the site. The cookies also help us to customize our marketing efforts through various media and formats.</p>
						<p>This website contains the ReadSpeaker Listen button. Cookies enable our products to recognize users and remember their preferences for how our Listen function works. The server will place a cookie on the user’s computer the first time he uses the ReadSpeaker service. The next time that the user activates the Listen button, the server will recognize the user and his preferred web-reading settings. Our cookies ensure better usability of our products for your end-users. Our cookies store user settings, such as reading speed, type of highlighting, and activation of a pop-up Listen button in case users have made changes to these settings. No other information is stored.</p>
						<h3>Do we disclose any information to outside parties?</h3>
						<p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>
						<h3>Online Privacy Policy Only</h3>
						<p>This online privacy policy applies only to information collected through our website and not to information collected offline.</p>
						<h3>Your Consent</h3>
						<p>By using our site, you consent to our privacy policy.</p>
						<h3>Changes to our Privacy Policy</h3>
						<p>If we decide to change our privacy policy, we will post those changes on this page.</p>
						<h3>Contact Us</h3>
						<p style={{ marginBottom: "2.5rem" }}>If there are any questions regarding this privacy policy you may contact us 
							<a href="http://shujutech.mywire.org/corporation?goto=contactUs" style={{ color: "blue", cursor: "pointer", paddingLeft: "0" }}> here.</a>
						</p>
					</div> 
					<Auth.BackWrapper onClick={() => navigate(-1)} style={{ float: 'right' }}>
						<Auth.BackIcon />
						{t('common.back')}
					</Auth.BackWrapper>
				</BaseForm.Item>
			</BaseForm>
		</Auth.FormWrapper>
	);
};

export default PrivacyPolicyPage;
